version: '3.3'
services:
  mysqldb:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tpachato
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: medguesmi/mohamedprojetcicd:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tpachato?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysqldb
